config/routes.rb
Pop3EmailGrabber::Application.routes.draw do
  devise_for :users, path: "auth", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  get '/' => "welcome#index"
  get 'dynamic_header' => "welcome#dynamic_header", format: "js"

  namespace :dashboard do
    get '/' => "mail_boxes#index"
    get '/search' => "searches#simple"
    resources :mail_boxes, except: [:show] do
      get 'check_upload_status' => "mail_boxes#check_upload_status"
      get 'change_job_status' => "mail_boxes#change_job_status"
      resources :emails, only: [:index, :show]
      member do
        post 'upload'
      end
    end
  end

  get '/*something' => 'errors#render_404'
end

app/models/email.rb
#coding: utf-8
class Email < ActiveRecord::Base
  validates :message_id, presence:   true,
                        uniqueness: true

  validates :from, :mail_box, presence: true

  belongs_to :mail_box

  has_attached_file :attach,
                    :url => "/system/:id.:extension"
  validates_attachment_content_type :attach, content_type: "application/zip"
end

app/models/mail_box.rb
require 'net/pop'
require 'fileutils'
require 'zip'

class MailBox < ActiveRecord::Base
  include AASM

  validates :login, :pop3_server, :domain, presence: true
  validates :pop3_server, format: {with: /pop.*/, message: "pop server address should start with pop"}
  
  belongs_to :user

  has_many :emails, dependent: :destroy
  scope :uploaded_boxes, -> { where(update_status: "processing") }
  
  aasm column: 'update_status' do 
    state :empty, initial: true
    state :processing
    state :failed
    state :complete
    
    event :to_process do
      transitions from: [:empty, :failed, :complete], to: :processing, on_transition: :set_current_job_id
    end
    
    event :to_complete do
      transitions from: :processing, to: :complete
    end
    
    event :to_failed do
      transitions from: :processing, to: :failed
    end
  end

  def set_current_job_id(job_id)
     self.update_attributes(current_job_id: job_id)
  end

  class << self
    def finish_update_status
      ["complete", "failed"]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  has_many :mail_boxes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper

  protected
    def after_sign_in_path_for(current_user)
      dashboard_path
    end
end

app/controllers/dashboard/application_controller.rb
#coding: utf-8
class Dashboard::ApplicationController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/dashboard/emails_controller.rb
#coding: utf-8
class Dashboard::EmailsController < Dashboard::ApplicationController
  inherit_resources
  before_filter :check_permissions
  belongs_to :mail_box
  defaults :route_prefix => "dashboard"
  respond_to :html

  protected
    def collection
      @emails ||= end_of_association_chain.paginate(page: params[:page], per_page: WillPaginate.per_page)
    end

    def check_permissions
      mailbox = MailBox.find_by_id(params[:mail_box_id])
      if mailbox
        redirect_to dashboard_path, alert: "Permission denied." unless mailbox.user_id == current_user.id
      else
        redirect_to dashboard_path, alert: "Mail box with id #{params[:mail_box_id]} doesn't exist."
      end
    end
end

app/controllers/dashboard/mail_boxes_controller.rb
#coding: utf-8
class Dashboard::MailBoxesController < Dashboard::ApplicationController
  inherit_resources
  defaults route_prefix: "dashboard"
  actions :all, except: :show
  respond_to :html

  #delete begin/rescue and move to lib/mail_box_uploader.rb
  def upload
    @mail_box = MailBox.where(id: params[:id]).first
    key, message = :notice, "Скачивание началось, это может занять некоторое время"
    begin
      if @mail_box && params[:password]
        @job_id = Uploader::MailBoxUploader.perform_async(params[:password], params[:id])
        @mail_box.to_process!(nil, @job_id)
        p "inspect mailbox #{@mail_box.inspect}"
      end
    rescue => ex
      Rails.logger.info "Caught exception: #{ex.message}"
      key = :alert
      message =
        case ex
          when Net::POPAuthenticationError
            "Неверный логин или пароль."
          when SocketError
            "Неверный адрес pop3-сервера."
          else
            "Неизвестная ошибка."
        end
    end
    redirect_to dashboard_path, key => message
  end

  def check_upload_status
    data = SidekiqStatus::Container.load(params[:job_id])
    render :json => { :status => data.status }
  end

  def change_job_status
    mail_box = MailBox.find_by(current_job_id: params[:job_id])
    key, message = :alert, "Произошла ошибка при загрузке писем с ящика #{mail_box.login}@#{mail_box.domain}"
    if mail_box
      MailBox.finish_update_status.include?(params[:job_status]) ? mail_box.send("to_#{params[:job_status]}!") : mail_box.to_failed!
      if params[:job_status] == "complete"
        key, message = :notice, "Письма с ящика #{mail_box.login}@#{mail_box.domain} скачены."
      end
    else
      p "Error, job doesn't exist"
    end
    redirect_to dashboard_path, key => message
  end

  protected
    def begin_of_association_chain
      current_user
    end

    def collection
      @mail_boxes ||= end_of_association_chain.paginate(page: params[:page], per_page: WillPaginate.per_page)
    end

    def permitted_params
      params.permit(:mail_box => [:login, :pop3_server, :domain])
    end
end

app/controllers/dashboard/searches_controller.rb
# coding: utf-8

class Dashboard::SearchesController < Dashboard::ApplicationController
  def simple
    unless params[:query].blank?
      @query = params[:query] 
      @emails = Email.search @query, page: params[:page], per_page: WillPaginate.per_page
    end
  end
end

app/controllers/errors_controller.rb
# coding: utf-8
class ErrorsController < ApplicationController
  def render_404
    render layout: false
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index;end

  def dynamic_header
    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def breadcrumbs(*args)
    bc = "<ol class=\"breadcrumb\">"
    args.flatten.each do |argument|
      bc += "<li>#{argument}</li>"
    end
    bc += "</ol>"
    bc.html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/mail_boxes/_ajax_requests.js.erb
<script type="text/javascript">
setInterval(function() {
  <% @boxes.each do |mail_box| %>
    $.ajax({
      url: "/dashboard/mail_boxes/<%= mail_box.id %>/check_upload_status",
      data: "job_id=<%= mail_box.current_job_id %>",
      success: function(data) {
        if(data.status == "complete" || data.status == "failed") {
          var job_status = data.status
          window.location.href = "/dashboard/mail_boxes/<%= mail_box.id %>/change_job_status?job_id=<%= mail_box.current_job_id %>&job_status="+job_status ;
        }
      }
    });
  <% end %>
}, 4000);
</script>

app/views/dashboard/mail_boxes/_auth_form.slim
.auth
  = form_tag "#", id: "password-form", method: "POST" do
    = label_tag :password
    = password_field_tag :password
    = submit_tag "Обновить", class: "btn btn-primary"

app/views/dashboard/mail_boxes/_form.slim
= semantic_form_for [:dashboard, resource] do |form|
  .mailbox-fields
    = form.input :login, as: :string
    = form.input :pop3_server, as: :string
    = form.input :domain, as: :string
    = form.action :submit, label: "Сохранить"

app/views/dashboard/mail_boxes/edit.slim
- provide :title, "Панель управления - Редактирование текущего ящика"
= render 'form'

app/views/dashboard/mail_boxes/index.slim
javascript:
 function PasswordPopup(box_id) {
    $('#popup-update').show();
    $('form#password-form').attr("action", "/dashboard/mail_boxes/"+box_id+"/upload");
    $('#popup-update').bPopup();
  }

- provide :title, "Панель управления - Все ящики пользователя"
= breadcrumbs ["<a href=\"/dashboard\">Панель управления</a>", "Все ящики пользователя"]
#popup-update
  = render 'auth_form'
table.table.table-hover
  thead
    tr
      th Логин
      th Домен
      th POP3 сервер
      th Последнее обновление
      th.center Управление
  - collection.each do |box|
    tr
      td = box.login
      td = box.domain
      td = box.pop3_server
      td = box.updated_at
      td.center
        a.update-link onclick="PasswordPopup(#{box.id});" href="#" title="Обновить"
          span.update-button.glyphicon.glyphicon-refresh
        a.show-link href="#{dashboard_mail_box_emails_path(box)}" title="Просмотр"
          span.show-button.glyphicon.glyphicon-list
        a.edit-link href="#{edit_dashboard_mail_box_path(box)}" title="Редактировать"
          span.edit-button.glyphicon.glyphicon-edit
        = link_to content_tag("span class=\"delete-button glyphicon glyphicon-remove\""), dashboard_mail_box_path(box), title: "Удалить", method: :delete, confirm: "Вы уверены?"
= will_paginate collection, renderer: BootstrapPagination::Rails

app/views/dashboard/mail_boxes/new.slim
- provide :title, "Панель управления - Добавление нового ящика"
= breadcrumbs ["<a href=\"/dashboard\">Панель управления</a>", "Добавить новый ящик"]
= render 'form'

app/views/dashboard/searches/simple.slim
- provide :title, "Панель управления | Результаты поиска по запросу #{@query} "
= breadcrumbs ["<a href=\"/dashboard\">Панель управления</a>","Результаты поиска по запросу #{@query}"]
- if @emails && @emails.size > 0
  table.table.table-hover
    thead
      th Отправитель
      th Получатель
      th Тема
      th.center Вложение
      th Просмотр
    - @emails.each do |email|
      tr
        td = email.from
        td = email.to
        td = email.subject
        td.center
          = raw email.attach.present? ? "<a href=\"#{email.attach.url}\" title=\"Скачать\"><span class=\"glyphicon glyphicon-download\"></span></a>" : "Нет"
        td
          = link_to "Просмотр",  dashboard_mail_box_email_path(email.mail_box, email)
  = will_paginate @emails, renderer: BootstrapPagination::Rails
- else
  p.search-not-found По запросу #{@query} ничего не найдено.

app/views/layouts/application.slim
doctype html
html
  head
    title = "Email Grabber | #{yield :title}"
    = stylesheet_link_tag "application.css"
    = yield :stylesheets
    = javascript_include_tag "application.js"
    = yield :javascripts
    = csrf_meta_tags
  body
   .container
     .header
       ul.nav.nav-pills.pull-right#dynamic_header
       h3.text-muted EmailGrabber
     - if flash[:notice] || flash[:alert]
       #flash-wrapper
         = raw "<div class=\"flash-notice\">#{flash[:notice]}</div>" if flash[:notice]
         = raw "<div class=\"flash-error\">#{flash[:alert]}</div>" if flash[:alert]
     - if current_user
       .button-wrapper
         a.btn.btn-primary.btn-lg href="#{new_dashboard_mail_box_path}" Добавить ящик
       .search-wrapper
         form.form-search action="/dashboard/search"
           .input-append
             input.span2.search-query type="text" name="query"
             button.search-btn href="/dashboard/search" Поиск
     = yield :breadcrumbs
     == yield
     .footer
       p one-man-team product 2014.
     script type='text/javascript' src='/dynamic_header.js'
     - if current_user
       - uploaded_boxes = current_user.mail_boxes.uploaded_boxes
       - if uploaded_boxes.size > 0
         - content_for :footer_javascripts
           = render 'dashboard/mail_boxes/ajax_requests.js.erb', object: @boxes = uploaded_boxes
     = yield :footer_javascripts

app/views/welcome/_header.slim
- unless current_user
  li.active
    a href="/" title="Главная" Главная
  li
    a href="/auth/register" title="Регистрация" Регистрация
  li
    a href="/auth/login" title="Войти" Войти
- else
  li
    a href= "/dashboard" title="Панель управления" Панель управления
  li
    = link_to "Выйти", destroy_user_session_path, method: :delete

app/views/welcome/dynamic_header.js.erb
$(document).ready(function(){
  $('#dynamic_header').append('<%= escape_javascript render 'header' %>');
});

app/views/welcome/index.slim
- provide :title, "Главная"
.jumbotron
  h1 App Heading!
  p.lead This is a same long description.
  a.btn.btn-lg.btn-success href='/auth/register' Зарегистрироваться!
.row.marketing
  .col-lg-6
    h4 Theses #1
    p Theses #1 description ....
  .col-lg-6
    h4 Theses #2
    p Theses #2 description ....